### ISSUE TITLE
Use scripts in the course project

### ISSUE THREAD

**Issue by YuliangXiaoYLX** [deepmind/surface-distance#13]
Hi all, I am currently working on my course project and I find that your scripts are very helpful on computing average hausdorff distance. I am confused what I should do before I can use your code in my project. Do I need to sign any documents before I can use the code? Hope to hear your response, thanks.

**Comment by SimonBiggs** [comment]
I'm not the original author of this project, however, they have released it under a permissive license:

https://github.com/deepmind/surface-distance/blob/master/LICENSE

You don't need to sign anything to use their code. Here's an overview of what their license means:

https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)

**Comment by YuliangXiaoYLX** [comment]
@SimonBiggs Thanks for your response!

**Comment by SimonBiggs** [comment]
My pleasure :)
